spring.application.name=cartrecovery

spring.datasource.url=jdbc:mysql://mysql:3306/cartrecovery
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.stat=OFF
logging.level.org.hibernate=ERROR

//kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.cart-update-event.group-id=cart-update-event-consumer-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.cart-update-events=cart-update-events

// notification kafka
spring.kafka.consumer.cart-recovery-notification.email.group-id=cart-recovery-notification-email-group
spring.kafka.consumer.cart-recovery-notification.sms.group-id=cart-recovery-notification-sms-group
spring.kafka.consumer.cart-recovery-notification.push.group-id=cart-recovery-notification-push-group

kafka.topic.cart-recovery-notification-topic=cart-recovery-notification


spring.jackson.time-zone=Asia/Kolkata
user.timezone=Asia/Kolkata

//redis
spring.data.redis.host=redis
spring.data.redis.port=6379